#!/bin/bash -e
INSTALL_LOC=/opt/BSCC
CPUINFO=`lscpu | grep "Architecture" | awk '{print $2}'`

#Check PC specs to see if it's ARM or X86 and grab the correct java version.
CPUINFO=`lscpu | grep "Architecture" | awk '{print $2}'`

 -# get real username		
 -if [ $UID = 0 ] && [ ! -z "$SUDO_USER" ]; then		
 -	USER="$SUDO_USER"		
 -else		
 -	USER="$(whoami)"		
 -fi


#Install Java for Arm.
do_arm() {
if [[ "$CPUINFO" == arm* ]]; then
wget -O java.tar.gz http://ftp.osuosl.org/pub/funtoo/distfiles/oracle-java/jdk-8u91-linux-arm32-vfp-hflt.tar.gz
mkdir /opt/java_jdk
tar zxvf java.tar.gz -C /opt/java_jdk --strip-components=1
rm java.tar.gz
update-alternatives --install "/usr/bin/java" "java" "/opt/java_jdk/bin/java" 1
update-alternatives --set java /opt/java_jdk/bin/java
. /etc/profile
fi
}

#Install Java for X64 PC's
do_x86() {
if [[ "$CPUINFO" == x86_64 ]]; then
wget -O java.tar.gz http://ftp.osuosl.org/pub/funtoo/distfiles/oracle-java/jre-8u92-linux-x64.tar.gz
mkdir /opt/java_jdk
tar zxvf java.tar.gz -C /opt/java_jdk --strip-components=1
rm java.tar.gz
update-alternatives --install "/usr/bin/java" "java" "/opt/java_jdk/bin/java" 1
update-alternatives --set java /opt/java_jdk/bin/java
. /etc/profile
#clear
fi
}

#Check Architecture
do_java() {
if [[ "$CPUINFO" == arm* ]]; then
do_arm
else
if [[ "$CPUINFO" == x86_64 ]]; then
do_x86
fi
fi
}

#Check for java install.
if [ ! -f /usr/bin/java ]; then
do_java
fi

chown -R $USER:$USER $INSTALL_LOC
chmod +x $INSTALL_LOC/Files/Greeting
chmod +x /usr/bin/BSCC
clear
echo "Ok everything is in order and you should now be able to run (BSCC Menu) and start your server builds."
sleep 3
echo "Starting BSCC for you the first time.."
sleep 3
BSCC
