#!/bin/bash -e
INSTALL_LOC=/opt/BSCC
CPUINFO=`lscpu | grep "Architecture" | awk '{print $2}'`

#Check PC specs to see if it's ARM or X86 and grab the correct java version.
CPUINFO=`lscpu | grep "Architecture" | awk '{print $2}'`

#Install Java for Arm.
do_arm() {
if [[ "$CPUINFO" == arm* ]]; then
wget -O java.tar.gz --no-check-certificate http://www.java.net/download/java/jdk8u102/archive/b03/binaries/jdk-8u102-ea-bin-b03-linux-arm-vfp-hflt-19_apr_2016.tar.gz
mkdir /opt/java_jdk
tar zxvf java.tar.gz -C /opt/java_jdk --strip-components=1
rm java.tar.gz
update-alternatives --install "/usr/bin/java" "java" "/opt/java_jdk/bin/java" 1
update-alternatives --set java /opt/java_jdk/bin/java
. /etc/profile
fi
}

#Install Java for X64 PC's
do_x86() {
if [[ "$CPUINFO" == x86_64 ]]; then
wget -O java.tar.gz --no-check-certificate --no-cookies --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u91-b14/jre-8u91-linux-x64.tar.gz && continue
mkdir /opt/java_jdk
tar zxvf java.tar.gz -C /opt/java_jdk --strip-components=1
rm java.tar.gz
update-alternatives --install "/usr/bin/java" "java" "/opt/java_jdk/bin/java" 1
update-alternatives --set java /opt/java_jdk/bin/java
. /etc/profile
#clear
fi
}

#Check Architecture
do_java() {
if [[ "$CPUINFO" == arm* ]]; then
do_arm
else
if [[ "$CPUINFO" == x86_64 ]]; then
do_x86
fi
fi
}

#Check for java install.
if [ ! -f /usr/bin/java ]; then
do_java
fi

chown -R $USER:$USER $INSTALL_LOC
chmod +x $INSTALL_LOC/Files/Greeting
chmod +x /usr/bin/BSCC
clear
echo "Ok everything is in order and you should now be able to run (BSCC Menu) and start your server builds."
sleep 3
echo "Starting BSCC for you the first time.."
sleep 3
BSCC
