#!/bin/bash

#latest log is slower then user check..
sleep 2
#######################################

source conf.cfg
SERVERLOG="$DIR/logs/latest.log"
PLAYER_LIST="players.list"
ONLINE_LIST="online.list"
tmp="online.bak"

IFS=$'\r\n' command eval 'MSG=($(cat RandomMSG.txt))'

GEN=$((RANDOM % ${#MSG[@]}))
MSG=${MSG[$GEN]}
if ! screen -list | grep -q "Minecraft"; then
echo "Server is not running"
exit $?
else

unset PLAYER
         PLAYER=`cat $SERVERLOG | grep "logged in with entity id" | awk '{print $4}' | cut -d "[" -f1 | tail -1`
sleep 2
        if [ $PLAYER ]; then
                if [ "$(grep $PLAYER $PLAYER_LIST)" != $PLAYER ]; then
                        echo "$PLAYER" >> $PLAYER_LIST
                        echo $PLAYER >> $ONLINE_LIST
                        screen -S Minecraft -p 0 -X stuff "say $PLAYER Welcome to the server. $(printf \\r)"
                else
                        echo "Your in"
                        grep -q -F $PLAYER $ONLINE_LIST || echo $PLAYER >> $ONLINE_LIST
                        screen -S Minecraft -p 0 -X stuff "say $PLAYER $MSG $(printf \\r)"
                fi
	fi
    fi
exit 0
