#!/bin/bash

#####This script will now be ran by default, It will allow you to control the server in many ways but i've outlined a few here. ####
#####How to use!, Create a Command block down and enter one of the few commands listed below. #####

#### Examples command: say @p Wished for an archive! (This would trigger the archive as long as you are an allowed user, Check /opt/BSCC/Files/Allowed.list###

LOG="/opt/BSCC/minecraft_server/logs/latest.log"

if [[ ! -f Allowed.list ]]; then
  touch Allowed.list
fi

check() {
if [[ ! -z "$RESTART" ]]; then
  screen -S Minecraft -p 0 -X stuff "tell $ALL Wish Granted! $(printf \\r)"
  sleep .5
  BSCC restart
fi

if [[ ! -z "$ARCHIVE" ]]; then
  screen -S Minecraft -p 0 -X stuff "tell $ALL Wish Granted! $(printf \\r)"
  sleep .5
  BSCC archive
fi

if [[ ! -z "$BACKUP" ]]; then
  screen -S Minecraft -p 0 -X stuff "tell $ALL Wish Granted! $(printf \\r)"
  sleep .5
  BSCC rsync
fi

if [[ ! -z "$STOP" ]]; then
  screen -S Minecraft -p 0 -X stuff "tell $ALL Wish Granted! $(printf \\r)"
  sleep .5
  BSCC stop
fi

if [[ ! -z "$STATS" ]]; then
  screen -S Minecraft -p 0 -X stuff "tell $ALL Wish Granted! $(printf \\r)"
  sleep .5
  BSCC stats
fi

if [[ ! -z "$BSCC" ]]; then
  screen -S Minecraft -p 0 -X stuff "tell $ALL Here are the list of commonds you can use on BSCC. $(printf \\r)"
  screen -S Minecraft -p 0 -X stuff "tell $ALL Restart: Restarts server. $(printf \\r)"
  screen -S Minecraft -p 0 -X stuff "tell $ALL Archive: Creates an archive. $(printf \\r)"
  screen -S Minecraft -p 0 -X stuff "tell $ALL Backup: Creates a backup of the server. $(printf \\r)"
  screen -S Minecraft -p 0 -X stuff "tell $ALL Stop: Stops the server. $(printf \\r)"
  screen -S Minecraft -p 0 -X stuff "tell $ALL Stats: Lists the states on the server. $(printf \\r)"
fi
}

while true; do
  unset ALLOWED RESTART ARCHIVE BACKUP STOP STATS
  info="[Server thread/INFO]:"
  OP="Allowed.list"
  ALL=$(cat $LOG | tail -n1 | grep -F "$info" | awk '{print $4}')

#Remove the <> from the original log so that it matches the Allowed.list file used for other things.
  ALL=$(echo "$ALL" | sed 's/<*//' | sed 's/>//')

  if [[ "$ALL" ]] && [[ "$(grep $ALL $OP)" = $ALL ]]; then
#Add <> for the newer versions of Minecraft logs
    ALLOWED="<$ALL>"
  fi

  RESTART=$(cat $LOG | tail -n1 | grep -F "$info $ALLOWED Restart")
  ARCHIVE=$(cat $LOG | tail -n1 | grep -F "$info $ALLOWED Archive")
  BACKUP=$(cat $LOG | tail -n1 | grep -F "$info $ALLOWED Backup")
  STOP=$(cat $LOG | tail -n1 | grep -F "$info $ALLOWED Stop")
  STATS=$(cat $LOG | tail -n1 | grep -F "$info $ALLOWED Stats")
  BSCC=$(cat $LOG | tail -n1 | grep -F "$info $ALLOWED BSCC")
  sleep 1
  check

done
