#!/bin/bash

#####This script will now be ran by default, It will allow you to control the server in many ways but i've outlined a few here. ####
#####How to use!, Create a Command block down and enter one of the few commands listed below. #####

#### Examples command: say @p Wished for an archive! (This would trigger the archive as long as you are an allowed user, Check /opt/BSCC/Files/Allowed.list###

LOG="/opt/BSCC/minecraft_server/logs/latest.log"

if [ ! -f Allowed.list ]; then
touch Allowed.list
fi

check() {
if [ ! -z "$RESTART" ]; then
screen -S Minecraft -p 0 -X stuff "say Wish Granted! $(printf \\r)"
sleep .5
BSCC restart > 2&1
fi
if [ ! -z "$ARCHIVE" ]; then
screen -S Minecraft -p 0 -X stuff "say Wish Granted! $(printf \\r)"
sleep .5
BSCC archive > 2&1
fi
if [ ! -z "$BACKUP" ]; then
screen -S Minecraft -p 0 -X stuff "say Wish Granted! $(printf \\r)"
sleep .5
BSCC rsync > 2&1
fi
if [ ! -z "$STOP" ]; then
screen -S Minecraft -p 0 -X stuff "say Wish Granted! $(printf \\r)"
sleep .5
BSCC stop > 2&1
fi
if [ ! -z "$STATS" ]; then
screen -S Minecraft -p 0 -X stuff "say Wish Granted! $(printf \\r)"
sleep .5
BSCC stats > 2&>1
fi
if [ ! -z "$MAPS" ]; then
screen -S Minecraft -p 0 -X stuff "say Wish Granted! $(printf \\r)"
sleep .5
BSCC map > 2&>1 &
fi
}

while true; do
unset ALLOWED RESTART ARCHIVE BACKUP STOP STATS MAPS
info="[Server thread/INFO]: [@]"
OP="Allowed.list"
ALL=$(cat $LOG | tail -n1 | grep -F "$info" | awk '{print $5}')
if [ "$ALL" ]; then
if [ "$(grep $ALL $OP)" = $ALL ]; then
ALLOWED="$ALL"
fi
fi
RESTART=$(cat $LOG | tail -n1 | grep -F "$info $ALLOWED Wished for restart!")
ARCHIVE=$(cat $LOG | tail -n1 | grep -F "$info $ALLOWED Wished for an archive!")
BACKUP=$(cat $LOG | tail -n1 | grep -F "$info $ALLOWED Wished to backup!")
STOP=$(cat $LOG | tail -n1 | grep -F "$info $ALLOWED Wished to end this world!")
STATS=$(cat $LOG | tail -n1 | grep -F "$info $ALLOWED Wished for stats!")
MAPS=$(cat $LOG | tail -n1 | grep -F "$info $ALLOWED Wished for maps!")
sleep 1
check
done
