#!/bin/bash
source conf.cfg 
SERVERLOG="$DIR/logs/latest.log" 
PLAYERSLIST="players.list" 

IFS=$'\r\n' command eval 'MSG=($(cat RandomMSG.txt))' 



x=0 
while x=1; do 
GEN=$((RANDOM % ${#MSG[@]})) 
MSG=${MSG[$GEN]}
	sleep 2
        PLAYER=`tail -2 $SERVERLOG | grep "logged in with entity id" | awk '{print $4}' | cut -d "[" -f1`
        if [ $PLAYER ]; then
                if [ "$(grep $PLAYER $PLAYERSLIST)" != $PLAYER ]; then
                        echo "$PLAYER" >> $PLAYERSLIST
                        $CONSOLE1 "say $PLAYER $WELCOME $CONSOLE2"
                else
			$CONSOLE1 "say $MSG $CONSOLE2"
		fi
        fi
                TESTPLAYER=`tail -2 $SERVERLOG | grep "logged in with entity id" | awk '{print $4}' | cut -d "[" -f1`
		LOGOUT=`tail -1 $SERVERLOG | grep "left the game" | awk '{print $4}'`
		if [ $LOGOUT ]; then
			if [ "$(grep $LOGOUT $PLAYERSLIST)" != $LOGOUT ]; then
                        $CONSOLE1 "say $PLAYER $WELCOME $CONSOLE2"
                else
                        $CONSOLE1 "say $MSG $CONSOLE2"
                fi
	fi done
