#!/bin/bash
INSTALL_LOC=/opt/BSCC
CONFIG=$INSTALL_LOC/Files/conf.cfg
###############################
### Version 1.9-1.9.1 upgrade ###
###############################

cd $INSTALL_LOC/Files

#All checks cleared.. Update
do_update() {
	cp $CONFIG $INSTALL_LOC/Files/conf.cfg.bak
	wget https://raw.githubusercontent.com/kicker22004/BSCC-MC-Edition/master/BSCC -O BSCC
	wget https://raw.githubusercontent.com/kicker22004/BSCC-MC-Edition/master/Files/conf.cfg -O conf.cfg
	wget https://raw.githubusercontent.com/kicker22004/BSCC-MC-Edition/master/Files/kit -O kit
	wget https://raw.githubusercontent.com/kicker22004/BSCC-MC-Edition/master/Files/watch_login -O watch_login
	clear
	sudo mv BSCC /usr/bin/
	sudo chmod +x /usr/bin/BSCC
	chmod +x /opt/BSCC/Files/kit
	chmod +x /opt/BSCC/Files/watch_login
#Grab old info and replace in new conf.cfg
	source $INSTALL_LOC/Files/conf.cfg.bak
	sed -i "s/MCVERSION=.*/MCVERSION=$MCVERSION/g" $CONFIG
	sed -i "s/SERVERJAR=.*/SERVERJAR=$SERVERJAR/g" $CONFIG
	sed -i "s/MINMEM=.*/MINMEM=$MINMEM/g" $CONFIG
	sed -i "s/MAXMEM=.*/MAXMEM=$MAXMEM/g" $CONFIG
	sed -i "s/ARGUMENTS=.*/ARGUMENTS=$ARGUMENTS/g" $CONFIG
	sed -i "s/check=.*/check=$check/g" $CONFIG
	sed -i "s/startonboot=.*/startonboot=$startonboot/g" $CONFIG
	sed -i "s/MCSREEN=.*/MCSCREEN=$MCSCREEN/g" $CONFIG
	exit 0
}

if [ -f /opt/BSCC/Files/conf.cfg ]; then
	do_update
else
	whiptail --msgbox --fb "Sorry it seems that your BSCC installation is not complete. Leaving." 20 60 0
	clear
	echo "No conf.cfg found in /opt/BSCC/Files/" ; exit 1
fi
exit 0
