#!/bin/bash
INSTALL_LOC=/opt/BSCC
CONFIG=$INSTALL_LOC/Files/conf.cfg
###############################
### Version 2.0.3-2.0.4 upgrade ###
###############################

cd $INSTALL_LOC/Files

do_changelog() {
        cat <<EOF >> changelog
1. Adding software for html2json.
EOF
whiptail --fb --title "BSCC 2.0.4 Changelog" --textbox changelog 20 60
rm changelog
}

do_servertype() {
while true; do
  FUN=$(whiptail --fb --title "User input needed" --menu "Please tell me what version you are currently running with BSCC."  --cancel-button Exit --ok-button Select 20 80 7 \
    "1 Vanilla" "|" \
    "2 Spigot" "|" \
    "3 FTB" "|" \
    3>&1 1>&2 2>&3)
  RET=$?
  if [ $RET -eq 1 ]; then
     exit 1
  elif [ $RET -eq 0 ]; then
    case "$FUN" in
      1\ *)  sed -i "s/SERVER_TYPE=.*/SERVER_TYPE=VANILLA/g" $CONFIG; break ;;
      2\ *)  sed -i "s/SERVER_TYPE=.*/SERVER_TYPE=SPIGOT/g" $CONFIG; break ;;
      3\ *)  sed -i "s/SERVER_TYPE=.*/SERVER_TYPE=FTB/g" $CONFIG;break ;;
      *) whiptail --msgbox "Programmer error: unrecognized option" 20 60 1 ;;
    esac || whiptail --msgbox "There was an error running option $FUN" 20 60 1
fi
done
}

#All checks cleared.. Update
do_update() {
	#Doing a one time update for html2json software.
	if [ ! -f /usr/bin/himalaya ]; then
	sudo apt-get -y update
	sudo apt-get -y upgrade
	sudo apt-get -y install npm node
	curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
	sudo apt-get -y install nodejs
	sudo npm install --global himalaya
	fi
	#This should be out after this update!. Placing in the install script.
	cp $CONFIG $INSTALL_LOC/Files/conf.cfg.bak
	wget https://raw.githubusercontent.com/kicker22004/BSCC-MC-Edition/master/BSCC -O BSCC
	wget https://raw.githubusercontent.com/kicker22004/BSCC-MC-Edition/master/Files/conf.cfg -O conf.cfg
	wget https://raw.githubusercontent.com/kicker22004/BSCC-MC-Edition/master/Files/kit -O kit
	wget https://raw.githubusercontent.com/kicker22004/BSCC-MC-Edition/master/Files/watch_login -O watch_login
	wget https://raw.githubusercontent.com/kicker22004/BSCC-MC-Edition/master/Files/update.sh -O update.sh
	clear
	sudo mv BSCC /usr/bin/
	sudo chmod +x /usr/bin/BSCC
	chmod +x /opt/BSCC/Files/kit
	chmod +x /opt/BSCC/Files/watch_login
	chmod +x /opt/BSCC/Files/update.sh
	rm $INSTALL_LOC/Files/spigot.list
#Grab old info and replace in new conf.cfg
	source $INSTALL_LOC/Files/conf.cfg.bak
	sed -i "s/MCVERSION=.*/MCVERSION=$MCVERSION/g" $CONFIG
	sed -i "s/SERVERJAR=.*/SERVERJAR=$SERVERJAR/g" $CONFIG
	sed -i "s/MINMEM=.*/MINMEM=$MINMEM/g" $CONFIG
	sed -i "s/MAXMEM=.*/MAXMEM=$MAXMEM/g" $CONFIG
	sed -i "s/ARGUMENTS=.*/ARGUMENTS=$ARGUMENTS/g" $CONFIG
	sed -i "s/check=.*/check=$check/g" $CONFIG
	sed -i "s/startonboot=.*/startonboot=$startonboot/g" $CONFIG
	sed -i "s/MCSREEN=.*/MCSCREEN=$MCSCREEN/g" $CONFIG
	chown -R $SUDO_USER:$SUDO_USER $INSTALL_LOC/Files/
        if [ -z $SERVER_TYPE ]; then
        whiptail --fb --msgbox "This update is a large update and bringing many new features, One of them is something many of you have asked me about. Server upgrading!, \
Well i'm glad to say it's been implemented (still betaish) but will require you to tell me what server you are currently running on BSCC. Thank you and I hope you enjoy." 20 60 0
        do_servertype
        fi
}

if [ -f /opt/BSCC/Files/conf.cfg ]; then
	do_changelog
	do_update
else
	whiptail --msgbox --fb "Sorry it seems that your BSCC installation is not complete. Leaving." 20 60 0
	clear
	echo "No conf.cfg found in /opt/BSCC/Files/" ; exit 1
fi
exit 0
