#!/bin/bash
SERVER_DIR="/opt/BSCC/minecraft_server/"
LOG="/opt/BSCC/minecraft_server/logs/latest.log"
TARGET="/opt/BSCC/PD_Backup/"
ON="onlineusers.list"
ALLTIME="Alltimeusers.list"

####################################
### First loads need delay       ###
####################################
WORLD=$(cat /opt/BSCC/minecraft_server/server.properties | grep -o "level-name.*" | cut -d "=" -f2)
for ((i=120;i>0;i=i-1)); do
  if [[ -z "$WORLD" ]]; then
    WORLD=$(cat /opt/BSCC/minecraft_server/server.properties | grep -o "level-name.*" | cut -d "=" -f2)
    echo -n "Looking for Custom World folder $i seconds"
    sleep 1
  else
    DIR="$SERVER_DIR$WORLD/stats/"
    PLAYERDATA="/opt/BSCC/minecraft_server/$WORLD/playerdata/"
    break
  fi
done

####################################
## Make file if they don't exist ###
## Make clean Onlineuser *bug*   ###
####################################
rm $ON

if [[ ! -f "$ON" ]]; then
  touch $ON
fi

if [[ ! -f "$ALLTIME" ]]; then
  touch $ALLTIME
fi

for ((i=120;i>0;i=i-1)); do
  if [[ ! -d "/opt/BSCC/minecraft_server/$WORLD" ]]; then
    echo -n "Waiting for World folder to populate."
    sleep 1
  else
    mkdir $DIR 2> /dev/null
    break
  fi
done

Vanilla_backup() {
## Look if user is new or now ###
  if [[ ! -d $TARGET$DECODEDUSERNAME ]]; then
    mkdir $TARGET$DECODEDUSERNAME
  fi

  VANILLA=$(cat conf.cfg | grep -o "VANILLA.*" | cut -d "=" -f2)

  if [[ $VANILLA = true ]]; then
    dt=$(date +"%Y_%m_%d-%H%M%S")
    cp $PLAYERDATA$PLAYERUUID.dat $TARGET$DECODEDUSERNAME/${DECODEDUSERNAME}_${dt}.dat
    cd $TARGET$DECODEDUSERNAME
    rm $(ls -1t $TARGET$DECODEDUSERNAME | tail -n +41) 2> /dev/null
    cd /opt/BSCC/Files/
  fi
}

inotifywait -q -m "$DIR" --format '%w%f' -e create,access | 
while read stats; do
#This will give us the Users UUID, we will use this to find the users name.
  PLAYERUUID=$(echo $stats | grep -o "stats.*" | cut -d "/" -f2 | cut -d "." -f1)
  CorrectUUID=$(echo $PLAYERUUID | sed 's/-//g')
  DECODEDUSERNAME=$(cat $ALLTIME | grep "$PLAYERUUID" | cut -d "=" -f1)

#Debugging options..##############
#echo "Playeruuid is: $PLAYERUUID"
#echo "CorrectUUID is :$CorrectUUID"
#echo "DECODEDUSERNAME is :$DECODEDUSERNAME"
###################################
  if [[ $DECODEDUSERNAME ]]; then
    Vanilla_backup
  fi
done
