#!/bin/bash

WORLD=$(cat /opt/BSCC/minecraft_server/server.properties | grep -o "level-name.*" | cut -d "=" -f2)
DIR="/opt/BSCC/minecraft_server/$WORLD/playerdata/"
PLAYERDATA="/opt/BSCC/minecraft_server/world/playerdata/"
TARGET="/opt/BSCC/PD_Backup/"
LOG="/opt/BSCC/minecraft_server/logs/latest.log"
ON="onlineusers.list"
ALLTIME="Alltimeusers.list"

Vanilla_backup() {
VANILLA=$(cat conf.cfg | grep -o "VANILLA.*" | cut -d "=" -f2)
if [ $VANILLA = true ]; then
dt=$(date +"%Y_%m_%d-%H%M%S")
cp $PLAYERDATA$PLAYERUUID.dat $TARGET$DECODEDUSERNAME/${DECODEDUSERNAME}_${dt}.dat
cd $TARGET$DECODEDUSERNAME
rm $(ls -1t $TARGET$DECODEDUSERNAME | tail -n +41) 2> /dev/null
cd /opt/BSCC/Files/
fi
}

trap() {
DECODEDUSERNAME=$(cat $ALLTIME | grep "$PLAYERUUID" | cut -d "=" -f1)
if [ -z "$DECODEDUSERNAME" ]; then
	echo "Something is wrong with Alltimeusers file.. Please check or reset it!"
else
	Vanilla_backup
        LOGOUT=$(cat $LOG | tail -n1 | grep -o "$DECODEDUSERNAME left the game")
if [ ! -z "$LOGOUT" ]; then
	sed -i '/'$DECODEDUSERNAME'/d' $ON
	Vanilla_backup
fi
fi
}

	inotifywait -m -q "$DIR" --format '%w%f' -e create |
	while read bailing; do
	dt=$(date +"%Y_%m_%d-%H%M%S")
	PLAYERUUID=$(echo $bailing | grep -o "playerdata.*" | cut -d "/" -f2 | cut -d "." -f1)
	trap
done
